###
# ESP settings
###
esp32:
  board: esp32dev
  framework:
    type: esp-idf
    
###
# Uart Settings
###
uart:
  id: uart_modbus
  tx_pin: 16
  rx_pin: 17
  baud_rate: 9600
  #baud_rate: 19200
  data_bits: 8
  stop_bits: 1
  parity: EVEN
  debug:
    direction: BOTH
