###
# Modbus Settings
###
modbus:
  id: modbus01
  uart_id: uart_modbus
  #send_wait_time: 2000ms

modbus_controller:
  - id: wtw
    address:          0x48 # Resolves to 72
    modbus_id:        modbus01
    setup_priority:   -10
    update_interval:  15s
    command_throttle: 200ms
    offline_skip_updates: 100
  - id: growatt
    address:          01 # the Modbus device addr, was 0x1
    modbus_id:        modbus01
    update_interval:  10s
    setup_priority:   -10
    command_throttle: 800ms



substitutions:
  skip_updates: "5"
  skip_updates_errors: "10"
  skip_updates_advanced: "100"
  modbus_id: wtw
  max_cap: "399"
  flap_max: "550"
  alert_icon: mdi:alert-circle
  max_error_number: "5"
  fan_speed_1: "100"
  fan_speed_2: "150"
  fan_speed_3: "200"
  fan_speed_4: "250"
  fan_speed_5: "300"
  fan_speed_6: "350"
  fan_speed_7: "399"