# Growatt START
sensor:
  - platform: modbus_controller
    modbus_controller_id: growatt
    name: "PV Status #"
    address: 3000
    register_type: "read"
#    internal: true
    accuracy_decimals: 0
    id: status
  - platform: modbus_controller
    modbus_controller_id: growatt
    name: "PV Actual Power"
    id: growatt_pac
    register_type: read
    address: 3023 # 0x000E
    value_type: U_DWORD
    unit_of_measurement: "W"
    state_class: total_increasing
    icon: mdi:solar-power
    accuracy_decimals: 1
    filters:
    - multiply: 0.1
    - clamp:
        min_value: 0
        max_value: 10000
        ignore_out_of_range: true
  - platform: modbus_controller
    modbus_controller_id: growatt
    name: "PV Actual Power String 1"
    id: growatt_ps1
    register_type: read
    address: 3005 # 0x000E
    value_type: U_DWORD
    unit_of_measurement: "W"
    accuracy_decimals: 1
    filters:
    - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: growatt
    name: "PV Actual Power String 2"
    id: growatt_ps2
    register_type: read
    address: 3009 # 0x000E
    value_type: U_DWORD
    unit_of_measurement: "W"
    accuracy_decimals: 1
    filters:
    - multiply: 0.1
  # - platform: modbus_controller
  #   modbus_controller_id: growatt
  #   name: "PV Frequentie"
  #   id: growatt_freq
  #   register_type: read
  #   address: 3025 # 0x000E
  #   value_type: U_WORD
  - platform: modbus_controller
    modbus_controller_id: growatt
    name: "PV Temperature"
    id: growatt_temp
    register_type: read
    address: 3093 # 0x000E
    value_type: U_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
    - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: growatt
    name: "PV Energy Today"
    id: growatt_etd
    register_type: read
    address: 3049 # 0x000E
    value_type: U_DWORD
    unit_of_measurement: "kWh"
    accuracy_decimals: 1
    filters:
    - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: growatt
    name: "PV Energy Total"
    id: growatt_ett
    register_type: read
    address: 3051 # 0x000E
    value_type: U_DWORD
    unit_of_measurement: "kWh"
    state_class: total_increasing
    device_class: "energy"
    accuracy_decimals: 1
    filters:
    - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: growatt
    name: "PV Derating Mode"
    id: growatt_dm
    register_type: read
    address: 3086 # 0x000E
    value_type: U_WORD
text_sensor:
  - platform: modbus_controller
    modbus_controller_id: growatt
    name: "Growatt Inverter Status"
    address: 0
    register_type: "read"
    raw_encode: HEXBYTES
    lambda: |-
      uint16_t value = modbus_controller::word_from_hex_str(x, 0);
      switch (value) {
        case 0: return std::string("Waiting");
        case 1: return std::string("Normal");
        case 3: return std::string("Fault");
        default: return std::string("Unknown");
      }
    icon: mdi:information
# Growatt r/w setting writers
switch:
  - platform: modbus_controller
    modbus_controller_id: growatt
    name: "Growatt On_Off"
    register_type: holding
    address: 0
    bitmask: 1 # Assuming 1 is ON, 0 is OFF
    entity_category: config
    icon: mdi:toggle-switch
# Growatt END
