esphome:
  name: modbus01
  friendly_name: Modbus01

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
#   level: VERY_VERBOSE

# Enable Home Assistant API
api:
  encryption:
    key: "B+ba66Wxv2+s9dmQ31gu/RnI7k5Lh+aJ5VbwZfGWgf8="

ota:
  - platform: esphome
    password: "47bfc75651fe35693d6d396028ddc04c"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Modbus Fallback Hotspot"
    password: "53eAbOSOuMxB"

web_server:
  port: 80
  version: 3
  
captive_portal:


